# role config
role = broker,gateway,ui

zk-addr = 172.31.101.89:2181

broker-transcript-num = 1

log_type = esx

es-cluster-name = elasticsearch

es-ip-addr = 47.109.67.130:9200

https_credit = false

es-username = elastic

es-password = aB.967426

### file type config
file_server_type = MINIO

# minio
minio_url = http://47.109.67.130:1026

minio_access_key = s6ycDmJoFu7Y2nbDhJ9R

minio_secret_key = CHlubXwEhPSb0E9LkOLmgmrSa943pXEIGHtnWLPw

minio_bucket_name = spider-node


### oss
oss_endpoint = xxxxxx

oss_keyId = xxxxxx

oss_keySecret = xxxxxxx

oss_bucketName = xxxxxx

bpmn_path = bpmn

sdk_path = sdk

### rpc-config
rpc-type = grpc

### spider-ui port
ui-port = 6140
### server-port
function-port = 8088

### mysql-config
mysql-host = 47.109.67.130

mysql-password = aB.967426

mysql-user = spider

mysql-port = 3306

mysql-database = spider

mysql-url = jdbc:mysql://47.109.67.130:3306/spider

mysql-driver-class-name = com.mysql.cj.jdbc.Driver

mysql-init-size = 20

mysql-min-idle = 20

limitation-interval = 20

limitation-number = 500

cluster_mode = N0_CENTER_MODE

### start_number
instance-number = 1

### spider-default
start_spider_node_is_new = true

### queue use type java/redis
queue_mode = java

### rocksdb-path
rocksdb_path = /usr/local/rocksdb/

### spider-agent-url
spider_agent_url_host = http://47.109.67.130:8082

### spider-code-ai-url
spider_code_ai_url = http://localhost:8084

### Host application port

host_application_port = 1238

K8S_BASE_URL = http://172.31.101.89:8444

K8S_TOKEN_KEY = eyJhbGciOiJSUzI1NiIsImtpZCI6ImVVN0lLNHFnQnMtcW84YmxYY09OT0FhU1E1NDZTSV9sOHFlSFMxUlFRSmcifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzcGlkZXItdmVydHgiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoic3BpZGVyLWFkbWluLXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InNwaWRlci1hZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjY4ZGI4ODMwLWI4YWEtNDZhYS05M2ZlLWJiZWQ4YzlkMTE1MCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpzcGlkZXItdmVydHg6c3BpZGVyLWFkbWluIn0.O0lf6juXe_Q37GpUDW8MzD7rMS7TIzgtnQMClYyCOOJ-rr1t6bDkzwCx2b4Y_NzWv9talK0MptOvI654oydOqBEQjZmIMuIKDtnp-XjYXuNh2g2msVso7mrW2UINqFMU-ULI3-BPODeloYf8QRLDp68HiHi-0bOfsGGBRVtSjJ6qGyV-bXWZs-n4sO87nVNwu8bhlVvBjSzMFhCT76csUVOaarGV0SuSrKjHX7LcRJsBP7XUuvzmAKht2cbJc-vOIWFC-TRY2k8StpOmdYmcemHAmYivaXQrciyAqGFPz0E8Q_l32Tj8olrvHRreB7LTzsOycHArd1c-bFeKKFZ90w

K8S_NAMESPACE = spider-vertx

