// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package cn.spider.framework.proto.grpc;

public final class SpiderTransferServer {
  private SpiderTransferServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_spider_framework_proto_grpc_TransferResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_spider_framework_proto_grpc_TransferResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_spider_framework_proto_grpc_TransferRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_spider_framework_proto_grpc_TransferRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016transfer.proto\022\036cn.spider.framework.pr" +
      "oto.grpc\"?\n\020TransferResponse\022\017\n\007message\030" +
      "\001 \001(\t\022\014\n\004code\030\002 \001(\005\022\014\n\004data\030\003 \001(\t\"h\n\017Tra" +
      "nsferRequest\022\016\n\006header\030\001 \001(\t\022\014\n\004body\030\003 \001" +
      "(\t\022\031\n\021taskComponentName\030\002 \001(\t\022\034\n\024taskCom" +
      "ponentVersion\030\004 \001(\t2\177\n\016TransferServer\022m\n" +
      "\010instruct\022/.cn.spider.framework.proto.gr" +
      "pc.TransferRequest\0320.cn.spider.framework" +
      ".proto.grpc.TransferResponseB\033B\024SpiderTr" +
      "ansferServerP\001\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cn_spider_framework_proto_grpc_TransferResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_spider_framework_proto_grpc_TransferResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_spider_framework_proto_grpc_TransferResponse_descriptor,
        new java.lang.String[] { "Message", "Code", "Data", });
    internal_static_cn_spider_framework_proto_grpc_TransferRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_spider_framework_proto_grpc_TransferRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_spider_framework_proto_grpc_TransferRequest_descriptor,
        new java.lang.String[] { "Header", "Body", "TaskComponentName", "TaskComponentVersion", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
