// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package cn.spider.framework.proto.grpc;

public interface TransferResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.spider.framework.proto.grpc.TransferResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int32 code = 2;</code>
   */
  int getCode();

  /**
   * <code>string data = 3;</code>
   */
  java.lang.String getData();
  /**
   * <code>string data = 3;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
