// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package cn.spider.framework.proto.grpc;

public interface TransferRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.spider.framework.proto.grpc.TransferRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string header = 1;</code>
   */
  java.lang.String getHeader();
  /**
   * <code>string header = 1;</code>
   */
  com.google.protobuf.ByteString
      getHeaderBytes();

  /**
   * <code>string body = 3;</code>
   */
  java.lang.String getBody();
  /**
   * <code>string body = 3;</code>
   */
  com.google.protobuf.ByteString
      getBodyBytes();

  /**
   * <code>string taskComponentName = 2;</code>
   */
  java.lang.String getTaskComponentName();
  /**
   * <code>string taskComponentName = 2;</code>
   */
  com.google.protobuf.ByteString
      getTaskComponentNameBytes();

  /**
   * <code>string taskComponentVersion = 4;</code>
   */
  java.lang.String getTaskComponentVersion();
  /**
   * <code>string taskComponentVersion = 4;</code>
   */
  com.google.protobuf.ByteString
      getTaskComponentVersionBytes();
}
