// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package cn.spider.framework.proto.grpc;

/**
 * <pre>
 **
 * 声明接口
 * </pre>
 *
 * Protobuf service {@code cn.spider.framework.proto.grpc.TransferServer}
 */
public  abstract class TransferServer
    implements com.google.protobuf.Service {
  protected TransferServer() {}

  public interface Interface {
    /**
     * <code>rpc instruct(.cn.spider.framework.proto.grpc.TransferRequest) returns (.cn.spider.framework.proto.grpc.TransferResponse);</code>
     */
    public abstract void instruct(
        com.google.protobuf.RpcController controller,
        cn.spider.framework.proto.grpc.TransferRequest request,
        com.google.protobuf.RpcCallback<cn.spider.framework.proto.grpc.TransferResponse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new TransferServer() {
      @java.lang.Override
      public  void instruct(
          com.google.protobuf.RpcController controller,
          cn.spider.framework.proto.grpc.TransferRequest request,
          com.google.protobuf.RpcCallback<cn.spider.framework.proto.grpc.TransferResponse> done) {
        impl.instruct(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.instruct(controller, (cn.spider.framework.proto.grpc.TransferRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return cn.spider.framework.proto.grpc.TransferRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return cn.spider.framework.proto.grpc.TransferResponse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc instruct(.cn.spider.framework.proto.grpc.TransferRequest) returns (.cn.spider.framework.proto.grpc.TransferResponse);</code>
   */
  public abstract void instruct(
      com.google.protobuf.RpcController controller,
      cn.spider.framework.proto.grpc.TransferRequest request,
      com.google.protobuf.RpcCallback<cn.spider.framework.proto.grpc.TransferResponse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return cn.spider.framework.proto.grpc.SpiderTransferServer.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.instruct(controller, (cn.spider.framework.proto.grpc.TransferRequest)request,
          com.google.protobuf.RpcUtil.<cn.spider.framework.proto.grpc.TransferResponse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return cn.spider.framework.proto.grpc.TransferRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return cn.spider.framework.proto.grpc.TransferResponse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends cn.spider.framework.proto.grpc.TransferServer implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void instruct(
        com.google.protobuf.RpcController controller,
        cn.spider.framework.proto.grpc.TransferRequest request,
        com.google.protobuf.RpcCallback<cn.spider.framework.proto.grpc.TransferResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        cn.spider.framework.proto.grpc.TransferResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          cn.spider.framework.proto.grpc.TransferResponse.class,
          cn.spider.framework.proto.grpc.TransferResponse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public cn.spider.framework.proto.grpc.TransferResponse instruct(
        com.google.protobuf.RpcController controller,
        cn.spider.framework.proto.grpc.TransferRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public cn.spider.framework.proto.grpc.TransferResponse instruct(
        com.google.protobuf.RpcController controller,
        cn.spider.framework.proto.grpc.TransferRequest request)
        throws com.google.protobuf.ServiceException {
      return (cn.spider.framework.proto.grpc.TransferResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        cn.spider.framework.proto.grpc.TransferResponse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:cn.spider.framework.proto.grpc.TransferServer)
}

